### ISSUE TITLE
version::Version partialEq does not use rpmvercmp()

### ISSUE THREAD

**Issue by utopiabound** [rpm-software-management/librpm.rs#11]
https://github.com/rpm-software-management/rpm/blob/master/lib/rpmvercmp.c

RPM Version comparison is complicated, and String =/= String isn't a good substitute.

e.g.
"1.05" == "1.5"

**Comment by tarcieri** [comment]
Yes, you're right, it shouldn't derive those (version comparisons are one of the unfinished items noted in the README)

**Comment by dralley** [comment]
I have a Rust version FWIW.  Seems to pass the test cases.

**Comment by tarcieri** [comment]
Yeah, pure Rust implementations should probably go in https://github.com/Richterrettich/rpm-rs

**Comment by dralley** [comment]
This can be closed by virtue of - the code just got deleted :)
