### ISSUE TITLE
New base image for CI

### ISSUE THREAD

**Issue by tarcieri** [rpm-software-management/librpm.rs#40]
We can't merge PRs since the current CI process is using CentOS 8, which is EOL. See e.g. #39.

I'm not too picky about the replacement. Perhaps Fedora? Or just installing librpm on GitHub Actions' `ubuntu-latest` would probably also work.

**Comment by Conan-Kudo** [comment]
Fixed with 8bd8c9f1e3c745b3e27e0e591a384dea89dfadee.
