### ISSUE TITLE
Fedora CI needs `dnf groupinstall "Development Tools"`

### ISSUE THREAD

**Issue by tarcieri** [rpm-software-management/librpm.rs#42]
It's failing because it can't find `cc`:

https://github.com/rpm-software-management/librpm.rs/runs/8039145443?check_suite_focus=true

```
error: linker `cc` not found
```

cc @Conan-Kudo

**Comment by Conan-Kudo** [comment]
That's weird... We install the `gcc` package right? That includes `/usr/bin/cc`.

**Comment by tarcieri** [comment]
Yeah I'm confused as well. Wasn't it working?

**Comment by Conan-Kudo** [comment]
Yeah, it was. I'm not sure what's going on now...

**Comment by Conan-Kudo** [comment]
This is fixed now.
